### ISSUE TITLE
Can't see lines in Sketch 3.8.3

### ISSUE THREAD

**Issue by vilbht** [herrhelms/radial-lines-sketch#1]
Hi there

I tried using the plugin (at the same settings as seen in your screenshot). I only seem to be getting a blank artboard with an empty folder called artboard-mask. Any fixes?

Thanks!

**Comment by herrhelms** [comment]
Interesting. Thank you for reporting this. I'll will look into it and get back w/ you.

**Comment by herrhelms** [comment]
So there have been some changes to the developer syntax in 3.8.3 therefore the plugin discontinued to work. I hope the recent commit fixes that. Let me know how it works for you. I made two releases (dependent on sketch version) available: https://github.com/herrhelms/radial-lines-sketch/releases

**Comment by vilbht** [comment]
Thank you for updating it! Works like a charm.

cheers!
